module.exports = {
  siteTitle: 'Nick Lewis Web Site',
  siteTitleAlt: 'Nick Lewis',
  siteLogo: '/logos/logo-512x512.png',
  siteUrl: 'https://nicklewis.digital',
  pathPrefix: '/',
  siteDescription: 'Find better leads with Nick Lewis.',
  siteRss: '/rss.xml',
  siteFBAppID: '',
  googleTagManagerID: '',
  userName: 'Nick Lewis',
  userTwitter: 'cupofdata',
  userLocation: 'Atlanta, GA',
  userDescription: '',
  copyright: 'Copyright © Nick Lewis 2018. All Rights Reserved.',
  themeColor: '#00d1b2',
  backgroundColor: '#ffffff',
}
