module.exports = {
  siteTitle: 'HeadForCode',
  siteTitleAlt: 'HeadForCode',
  siteLogo: '/logos/logo-512x512.png',
  siteUrl: 'https://headforcode.com',
  pathPrefix: '/',
  siteDescription: 'HeadForCode web and app consultancy',
  siteRss: '/rss.xml',
  siteFBAppID: '',
  googleTagManagerID: '',
  userName: 'Nick Lewis',
  userTwitter: 'headforcode',
  userLocation: 'Farnborough, UK',
  userDescription: '',
  copyright: 'Copyright © HEadForCode 2018. All Rights Reserved.',
  themeColor: '#00d1b2',
  backgroundColor: '#ffffff',
}
